### PR TITLE
Docker build updates

### PR DESCRIPTION
**Pull request by andycottonpih**
These updates switch the build and run containers to use the openmrs-core image.
The docker  is now setup to build 4 versions of the pihemr.  The image can be run as zl, ces, pihsl, or pihliberia.

### CODE REVIEW

**Comment by andycottonpih** [comment]
New draft PR to let everyone look at the current state of the docker build.  @mseaton @mogoodrich @chibongho @cioan @lnball

**Review by mseaton — APPROVED** [review]
Looks good to me!  Is there a README or can we include a script that provides information on how these are intended to be built?  What commands would one run to use this dockerfile to produce the 5 different images it seems capable of producing?

**Comment by andycottonpih** [comment]
This will produce all 5 with "docker build ." It no longer requires arguments for the build process.  I can update the readme with information on building and running the image.  Do you think I should also include a sample compose.yaml file?

**Comment by mseaton** [comment]
Where are the images given a specific name/tag?  And yes, a sample compose.yaml file would be great.

**Pull request merged**
